name: rAPId Integration Tests

on:
  workflow_dispatch:

  pull_request:
    types:
      - opened

jobs:
  run-ui-test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install packages
        run: |
          cd ui
          npm install

      - name: Install playwright browsers
        run: |
          cd ui
          npx playwright install-deps
          npm install @playwright/test -D

      - name: Run playwright tests
        run: make ui-test-e2e
        env:
          DOMAIN_NAME: ${{ secrets.E2E_DOMAIN_NAME }}
          RESOURCE_PREFIX: ${{ secrets.E2E_RESOURCE_PREFIX }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
